import { useState } from 'react';
import { jsPDF } from 'jspdf';
import { PRIVACY_NOTICE } from '../../utils/privacyNotice';
import { useDirectory } from '../../context/DirectoryContext';
import { useAuth } from '../../context/AuthContext';
import { useChat } from '../../context/ChatContext';
import MinistryOrbit from '../UI/MinistryOrbit';

export default function DirectoryView() {
    const { members, addMember, updateMember, deleteMember } = useDirectory();
    const { userRole, checkPermission } = useAuth();
    const { startPrivateChat } = useChat();
    const [selectedMember, setSelectedMember] = useState(null);
    const [searchTerm, setSearchTerm] = useState('');
    const [isEditing, setIsEditing] = useState(false);

    // saveMembers and generateMemberId removed as they are now in context


    const handleCreate = () => {
        const newMember = {
            // id will be generated by context
            memberId: '',
            photo: '',
            fullName: '',
            address: '',
            birthDate: '',
            phone: '',
            email: '',
            social: '',
            civilStatus: 'soltero',
            spouse: '',
            children: '',
            bloodType: '',
            allergies: '',
            illnesses: '',
            medications: '',
            emergencyName: '',
            emergencyPhone: '',
            baptismDate: '',
            confirmationDate: '',
            marriageDate: '',
            ministryOrder: 'Laico',
            currentMinistry: '',
            ministryOrder: 'Laico',
            currentMinistry: '',
            spiritualGifts: '',
            regularAttendance: false,
            notes: '',
            isNew: true
        };
        setSelectedMember(newMember);
        setIsEditing(true);
    };



    const handlePhotoChange = (e) => {
        const file = e.target.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onloadend = () => {
                setSelectedMember(prev => ({ ...prev, photo: reader.result }));
            };
            reader.readAsDataURL(file);
        }
    };

    const handleDownloadForm = async () => {
        const doc = new jsPDF();

        // --- CONFIGURATION ---
        // --- CONFIGURATION ---
        const marginLeft = 20;
        const toggleY = 10; // Vertical spacing increment
        let y = 35; // Start Y position

        // Load Logo
        const logoUrl = "https://raw.githubusercontent.com/Iglesiaiacg/cuatroliturgias/main/Emblema%20de%20la%20Iglesia%20Anglicana.png";
        try {
            const img = new Image();
            img.src = logoUrl;
            img.crossOrigin = "Anonymous";
            await new Promise((resolve) => {
                img.onload = resolve;
                img.onerror = resolve; // Continue even if logo fails
            });

            // Calculate Aspect Ratio
            const imgWidth = img.width;
            const imgHeight = img.height;
            const targetWidth = 25;
            const scaleFactor = targetWidth / imgWidth;
            const targetHeight = imgHeight * scaleFactor;

            doc.addImage(img, 'PNG', marginLeft, 20, targetWidth, targetHeight);
        } catch (e) {
            console.error("Could not load logo", e);
        }

        // --- HEADER ---
        doc.setFont("times", "bold");
        doc.setFontSize(22);
        doc.text("IGLESIA ANGLICANA", 105, 25, { align: "center" });
        doc.text("COMUNIDAD DE GRACIA", 105, 33, { align: "center" });

        doc.setFontSize(10);
        doc.setFont("times", "italic");
        doc.text("Membresía y Cuidado Pastoral", 105, 40, { align: "center" });

        doc.setLineWidth(0.5);
        // doc.line(marginLeft, 45, marginRight, 45); // Separator line removed

        y = 55;

        // Helper for Lines
        const drawField = (label, x, width, valY) => {
            doc.setFont("times", "bold");
            doc.setFontSize(10);
            doc.text(label, x, valY);

            // Draw underline for writing
            const labelWidth = doc.getTextWidth(label);
            const lineStart = x + labelWidth + 2;
            const lineEnd = x + width;

            doc.setLineWidth(0.1);
            doc.setDrawColor(150); // Grey line
            doc.line(lineStart, valY + 1, lineEnd, valY + 1);
            doc.setDrawColor(0); // Reset black
        };

        const drawSection = (title) => {
            doc.setFont("times", "bold");
            doc.setFontSize(12);
            doc.setTextColor(153, 27, 27); // Red-800
            doc.text(title, marginLeft, y);
            doc.setTextColor(0);
            y += 8;
        };

        // --- FOTO PLACEHOLDER (Right side) ---
        doc.setDrawColor(200);
        doc.rect(160, 55, 30, 40);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("FOTO", 175, 75, { align: "center" });
        doc.setTextColor(0);

        // --- I. DATOS PERSONALES ---
        drawSection("I. DATOS PERSONALES");

        drawField("Nombre Completo:", marginLeft, 135, y);
        y += toggleY;

        drawField("Fecha de Nacimiento:", marginLeft, 60, y);
        drawField("Lugar:", 90, 65, y); // x=90, w=65 (ends at 155)
        y += toggleY;

        drawField("Estado Civil:", marginLeft, 60, y);
        drawField("Profesión/Oficio:", 90, 65, y);
        y += toggleY;

        drawField("Domicilio Completo:", marginLeft, 135, y);
        y += toggleY;

        // Small note under domicile
        doc.setFontSize(8);
        doc.setFont("times", "italic");
        doc.setTextColor(100);
        doc.text("(Calle, Número, Colonia, C.P.)", marginLeft, y - 4);
        doc.setTextColor(0);
        y += 5; // Extra spacing after section

        // --- II. CONTACTO ---
        drawSection("II. INFORMACIÓN DE CONTACTO");

        drawField("Teléfono Casa:", marginLeft, 80, y);
        drawField("Celular / WhatsApp:", 110, 80, y);
        y += toggleY;

        drawField("Correo Electrónico:", marginLeft, 170, y);
        y += toggleY + 5;

        // --- III. SALUD ---
        drawSection("III. SALUD Y SEGURIDAD (VITAL)");

        drawField("Tipo de Sangre:", marginLeft, 80, y);
        drawField("Alergias:", 110, 80, y);
        y += toggleY;

        drawField("Padecimientos Crónicos:", marginLeft, 170, y);
        y += toggleY;

        drawField("Medicamentos Actuales:", marginLeft, 170, y);
        y += toggleY;

        doc.setFillColor(254, 242, 242); // Light red bg
        doc.rect(marginLeft, y - 5, 170, 12, 'F');
        drawField("EN CASO DE EMERGENCIA AVISAR A:", marginLeft + 2, 166, y);
        y += (toggleY / 2);
        doc.setFontSize(8);
        doc.text("(Nombre y Teléfono)", marginLeft + 2, y);
        y += toggleY + 5;

        // --- IV. VIDA SACRAMENTAL ---
        drawSection("IV. VIDA SACRAMENTAL");

        drawField("Bautismo (Fecha/Lugar):", marginLeft, 170, y);
        y += toggleY;
        drawField("Confirmación (Fecha/Lugar):", marginLeft, 170, y);
        y += toggleY;
        drawField("Matrimonio (Fecha/Cónyuge):", marginLeft, 170, y);
        y += toggleY + 5;

        // --- V. VIDA MINISTERIAL ---
        drawSection("V. VIDA MINISTERIAL");

        doc.setFont("times", "bold");
        doc.setFontSize(10);
        doc.text("Orden Eclesiástico:", marginLeft, y);

        // Checkboxes
        const roles = ["Laico", "Presbítero", "Diácono", "Ministro Laico"];
        let xPos = marginLeft + 35;
        roles.forEach(role => {
            doc.rect(xPos, y - 3, 4, 4);
            doc.text(role, xPos + 6, y);
            xPos += 35;
        });
        y += toggleY;

        drawField("Ministerio Actual:", marginLeft, 170, y);
        y += toggleY;
        drawField("Dones Espirituales:", marginLeft, 170, y);
        y += toggleY + 10;

        // --- FOOTER / PRIVACY PREVIEW ---
        doc.setLineWidth(0.5);
        // doc.line(marginLeft, 270, marginRight, 270); // Separator line removed
        doc.setFontSize(8);
        doc.setFont("times", "italic");
        doc.text("Este documento es confidencial y para uso exclusivo de la administración pastoral.", 105, 275, { align: "center" });
        doc.text("Consulte el Aviso de Privacidad Integral al reverso.", 105, 279, { align: "center" });

        // --- PAGE 2: PRIVACY NOTICE ---
        doc.addPage();

        // Header Page 2
        doc.setFontSize(16);
        doc.setFont("times", "bold");
        doc.text("AVISO DE PRIVACIDAD INTEGRAL", 105, 20, { align: "center" });

        doc.setFontSize(10);
        doc.setFont("times", "normal");

        // Split text for layout
        const splitText = doc.splitTextToSize(PRIVACY_NOTICE, 170);
        doc.text(splitText, marginLeft, 35);

        // Signatures
        let ySig = 265;
        doc.line(40, ySig, 90, ySig);
        doc.text("Firma del Fiel", 65, ySig + 5, { align: "center" });

        doc.line(120, ySig, 170, ySig);
        doc.text("Firma del Párroco/Responsable", 145, ySig + 5, { align: "center" });

        doc.save("Formulario_Membresia_IACG.pdf");
    };

    const handleSave = (e) => {
        e.preventDefault();
        if (!selectedMember.fullName) return;

        if (selectedMember.isNew) {
            const { isNew, ...dataToSave } = selectedMember;
            const newMember = addMember(dataToSave);
            setSelectedMember(newMember);
        } else {
            updateMember(selectedMember.id, selectedMember);
        }

        setIsEditing(false);
    };

    const handleDelete = () => {
        if (!confirm('¿Estás seguro de eliminar este registro?')) return;
        deleteMember(selectedMember.id);
        setSelectedMember(null);
        setIsEditing(false);
    };

    const normalizeText = (text) => {
        return text
            ? text.toString().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")
            : "";
    };

    const filteredMembers = members.filter(m => {
        const term = normalizeText(searchTerm);
        const name = normalizeText(m.fullName);
        const phone = normalizeText(m.phone);
        const id = normalizeText(m.memberId);

        return name.includes(term) || phone.includes(term) || id.includes(term);
    });

    return (
        <div className="flex flex-col md:flex-row neumorphic-card overflow-hidden h-[calc(100vh-140px)] animate-fade-in">
            {/* Sidebar List (Hidden on mobile if member selected) */}
            <div className={`${selectedMember ? 'hidden md:flex' : 'flex'} w-full md:w-1/3 min-w-[300px] border-r border-gray-200 flex-col bg-transparent h-full`}>
                <div className="p-4 border-b border-gray-100 dark:border-white/5 space-y-3">
                    <div className="flex justify-between items-center">
                        <h2 className="text-lg font-bold text-gray-800 dark:text-white flex items-center gap-2">
                            <span className="material-symbols-outlined text-primary">groups</span>
                            Fieles
                            <span className="bg-gray-100 dark:bg-white/10 text-gray-600 text-xs px-2 py-0.5 rounded-full">{members.length}</span>
                        </h2>
                        {(userRole === 'admin' || (checkPermission && checkPermission('manage_directory'))) && (
                            <button
                                onClick={handleCreate}
                                className="btn-primary p-2"
                                title="Nuevo Fiel"
                            >
                                <span className="material-symbols-outlined text-xl">add_circle</span>
                            </button>
                        )}
                    </div>
                    <div className="relative">
                        <span className="material-symbols-outlined absolute left-3 top-2.5 text-gray-500 text-sm">search</span>
                        <input
                            type="text"
                            placeholder="Buscar por nombre..."
                            value={searchTerm}
                            onChange={e => setSearchTerm(e.target.value)}
                            className="w-full bg-gray-100 dark:bg-black/20 pl-9 pr-4 py-2 rounded-lg text-sm border-none focus:ring-2 focus:ring-primary/20 outline-none"
                        />
                    </div>
                </div>

                <div className="flex-1 overflow-y-auto">
                    {filteredMembers.length === 0 ? (
                        <div className="p-8 text-center text-gray-500">
                            <span className="material-symbols-outlined text-4xl mb-2 opacity-50">person_off</span>
                            <p className="text-sm">No se encontraron fieles</p>
                        </div>
                    ) : (
                        <div className="divide-y divide-gray-50 dark:divide-white/5">
                            {filteredMembers.map(member => (
                                <button
                                    key={member.id}
                                    onClick={() => { setSelectedMember(member); setIsEditing(false); }}
                                    className={`w-full text-left p-4 hover:bg-gray-50 dark:hover:bg-white/5 transition-colors flex items-center gap-3 ${selectedMember?.id === member.id ? 'bg-red-50 dark:bg-red-900/10 border-l-4 border-primary' : 'border-l-4 border-transparent'}`}
                                >
                                    <div className="w-10 h-10 rounded-full bg-gray-200 dark:bg-gray-700 flex items-center justify-center text-gray-600 font-bold text-lg shrink-0">
                                        {member.fullName.charAt(0).toUpperCase()}
                                    </div>
                                    <div className="overflow-hidden">
                                        <h3 className={`font-bold truncate ${selectedMember?.id === member.id ? 'text-primary' : 'text-gray-800 dark:text-gray-200'}`}>
                                            {member.fullName}
                                        </h3>
                                        <p className="text-xs text-gray-600 truncate icon-text">
                                            {member.phone || 'Sin teléfono'}
                                        </p>
                                    </div>
                                </button>
                            ))}
                        </div>
                    )}
                </div>
            </div>

            {/* Main Content / Form */}
            <div className={`${!selectedMember ? 'hidden md:flex' : 'flex'} flex-1 overflow-y-auto bg-gray-50/50 dark:bg-black/5 p-4 md:p-8 flex-col`}>
                {/* Mobile Back Button */}
                {selectedMember && (
                    <button
                        onClick={() => setSelectedMember(null)}
                        className="md:hidden mb-4 flex items-center text-gray-600 hover:text-primary transition-colors font-bold text-sm"
                    >
                        <span className="material-symbols-outlined mr-1">arrow_back</span>
                        Volver a la lista
                    </button>
                )}
                {selectedMember ? (
                    <div className="max-w-3xl mx-auto">
                        <div className="flex flex-col md:flex-row justify-between items-start mb-6 gap-4">
                            <div className="flex items-center gap-4 w-full md:w-auto">
                                <div className="relative group shrink-0">
                                    {/* ORBITAL USER CARD (Mini Version) */}
                                    <div className="scale-75 origin-top-left -m-4">
                                        <MinistryOrbit
                                            photo={selectedMember.photo}
                                            initial={selectedMember.fullName ? selectedMember.fullName.charAt(0).toUpperCase() : '?'}
                                            role={selectedMember.ministryOrder || 'Laico'}
                                            ministries={[
                                                { id: 'min1', icon: 'volunteer_activism', label: selectedMember.currentMinistry || 'Servicio', color: 'text-primary' },
                                                { id: 'min2', icon: 'spa', label: selectedMember.spiritualGifts || 'Dones', color: 'text-blue-600' }
                                            ]}
                                        />
                                    </div>

                                    {isEditing && (
                                        <label className="absolute inset-0 flex items-center justify-center bg-black/50 text-white opacity-0 group-hover:opacity-100 cursor-pointer rounded-full transition-opacity z-20" style={{ top: '20px', left: '20px', width: '80px', height: '80px' }}>
                                            <span className="material-symbols-outlined text-sm">upload</span>
                                            <input type="file" accept="image/*" className="hidden" onChange={handlePhotoChange} />
                                        </label>
                                    )}
                                </div>
                                <div className="mt-4 md:mt-0">
                                    <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
                                        {selectedMember.fullName || 'Nuevo Registro'}
                                    </h2>
                                    <p className="text-sm text-gray-600 mt-1">
                                        {selectedMember.memberId ? (
                                            <span className="inline-flex items-center px-2.5 py-1 rounded-md text-xs font-bold bg-purple-100 text-purple-800 border border-purple-200 shadow-sm">
                                                {selectedMember.memberId}
                                            </span>
                                        ) : (
                                            <span className="text-xs italic text-gray-500">ID Pendiente</span>
                                        )}
                                    </p>
                                </div>
                            </div>
                            <div className="flex flex-wrap gap-2 w-full md:w-auto">
                                <button
                                    onClick={() => startPrivateChat(selectedMember)}
                                    disabled={!selectedMember.id}
                                    className="btn-secondary"
                                    title="Enviar Mensaje Privado"
                                >
                                    <span className="material-symbols-outlined text-sm">chat</span>
                                    <span className="hidden md:inline">MENSAJE</span>
                                </button>
                                <button
                                    onClick={handleDownloadForm}
                                    className="btn-secondary"
                                    title="Descargar Formulario en Blanco"
                                >
                                    <span className="material-symbols-outlined text-sm">description</span>
                                    <span className="hidden md:inline">FORMULARIO</span>
                                </button>
                                {!isEditing ? (
                                    (userRole === 'admin' || (checkPermission && checkPermission('manage_directory'))) && (
                                        <>
                                            <button
                                                onClick={handleDelete}
                                                className="btn-danger"
                                            >
                                                ELIMINAR
                                            </button>
                                            <button
                                                onClick={() => setIsEditing(true)}
                                                className="btn-primary"
                                            >
                                                <span className="material-symbols-outlined text-sm">edit</span>
                                                EDITAR
                                            </button>
                                        </>
                                    )
                                ) : (
                                    <>
                                        <button
                                            onClick={() => selectedMember.isNew ? setSelectedMember(null) : setIsEditing(false)}
                                            className="btn-ghost"
                                        >
                                            CANCELAR
                                        </button>
                                        <button
                                            onClick={handleSave}
                                            disabled={!selectedMember.fullName}
                                            className="btn-primary"
                                        >
                                            <span className="material-symbols-outlined text-sm">save</span>
                                            GUARDAR
                                        </button>
                                    </>
                                )}
                            </div>
                        </div>

                        {/* Form Fields */}
                        <div className="bg-white dark:bg-surface-dark rounded-xl shadow-sm border border-gray-100 dark:border-white/5 overflow-hidden">
                            {/* Section 1: Personal */}
                            <div className="p-6 border-b border-gray-100 dark:border-white/5">
                                <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4 flex items-center gap-2">
                                    <span className="material-symbols-outlined">person</span> Datos Personales
                                </h3>
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                    <Field label="Nombre Completo" value={selectedMember.fullName} onChange={v => setSelectedMember({ ...selectedMember, fullName: v })} editing={isEditing} placeholder="Ej. Juan Pérez" focus />
                                    <Field label="Fecha de Nacimiento" type="date" value={selectedMember.birthDate} onChange={v => setSelectedMember({ ...selectedMember, birthDate: v })} editing={isEditing} />
                                    <Field label="Estado Civil" type="select" options={['Soltero/a', 'Casado/a', 'Viudo/a', 'Divorciado/a', 'Unión Libre']} value={selectedMember.civilStatus} onChange={v => setSelectedMember({ ...selectedMember, civilStatus: v })} editing={isEditing} />
                                    <Field label="Domicilio" value={selectedMember.address} onChange={v => setSelectedMember({ ...selectedMember, address: v })} editing={isEditing} placeholder="Calle, Número, Colonia" />
                                </div>
                            </div>

                            {/* Section 2: Contact */}
                            <div className="p-6 border-b border-gray-100 dark:border-white/5 bg-gray-50/30 dark:bg-white/5">
                                <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4 flex items-center gap-2">
                                    <span className="material-symbols-outlined">contact_phone</span> Contacto
                                </h3>
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                    <Field label="Teléfono / Celular" value={selectedMember.phone} onChange={v => setSelectedMember({ ...selectedMember, phone: v })} editing={isEditing} placeholder="555-123-4567" />
                                    <Field label="Email" type="email" value={selectedMember.email} onChange={v => setSelectedMember({ ...selectedMember, email: v })} editing={isEditing} placeholder="correo@ejemplo.com" />
                                    <Field label="Redes Sociales" value={selectedMember.social} onChange={v => setSelectedMember({ ...selectedMember, social: v })} editing={isEditing} placeholder="Facebook, Instagram..." colSpan={2} />
                                </div>
                            </div>

                            {/* Section 3: Medical (Vital) */}
                            <div className="p-6 border-b border-gray-100 dark:border-white/5">
                                <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4 flex items-center gap-2">
                                    <span className="material-symbols-outlined">medical_services</span> Salud (Vital)
                                </h3>
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                                    <Field label="Tipo de Sangre" value={selectedMember.bloodType} onChange={v => setSelectedMember({ ...selectedMember, bloodType: v })} editing={isEditing} placeholder="O+" />
                                    <Field label="Alergias" value={selectedMember.allergies} onChange={v => setSelectedMember({ ...selectedMember, allergies: v })} editing={isEditing} placeholder="Penicilina, Nueces..." colSpan={2} />
                                    <Field label="Enfermedades Crónicas" value={selectedMember.illnesses} onChange={v => setSelectedMember({ ...selectedMember, illnesses: v })} editing={isEditing} placeholder="Diabetes, Hipertensión..." colSpan={3} />
                                </div>
                            </div>

                            {/* Section 4: Family */}
                            <div className="p-6 bg-gray-50/30 dark:bg-white/5">
                                <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4 flex items-center gap-2">
                                    <span className="material-symbols-outlined">diversity_3</span> Familia
                                </h3>
                                <div className="grid grid-cols-1 gap-6">
                                    <Field label="Cónyuge" value={selectedMember.spouse} onChange={v => setSelectedMember({ ...selectedMember, spouse: v })} editing={isEditing} placeholder="Nombre del esposo/a" />
                                    <div className="col-span-1">
                                        <label className="block text-xs font-bold text-gray-600 uppercase mb-1">Hijos</label>
                                        {isEditing ? (
                                            <textarea
                                                value={selectedMember.children}
                                                onChange={e => setSelectedMember({ ...selectedMember, children: e.target.value })}
                                                className="w-full bg-white dark:bg-black/20 border border-gray-200 dark:border-white/10 rounded-lg p-3 text-sm focus:ring-2 focus:ring-primary/20 outline-none h-24 resize-none"
                                                placeholder="Lista de hijos y edades..."
                                            />
                                        ) : (
                                            <div className="text-sm text-gray-800 dark:text-gray-200 whitespace-pre-wrap min-h-[1.5rem]">{selectedMember.children || '—'}</div>
                                        )}
                                    </div>
                                </div>
                            </div>
                            {/* Section 5: Sacraments */}
                            <div className="p-6 border-t border-gray-100 dark:border-white/5">
                                <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4 flex items-center gap-2">
                                    <span className="material-symbols-outlined">church</span> Vida Sacramental
                                </h3>
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                                    <Field label="Fecha Bautismo" type="date" value={selectedMember.baptismDate} onChange={v => setSelectedMember({ ...selectedMember, baptismDate: v })} editing={isEditing} />
                                    <Field label="Fecha Confirmación" type="date" value={selectedMember.confirmationDate} onChange={v => setSelectedMember({ ...selectedMember, confirmationDate: v })} editing={isEditing} />
                                    <Field label="Fecha Matrimonio" type="date" value={selectedMember.marriageDate} onChange={v => setSelectedMember({ ...selectedMember, marriageDate: v })} editing={isEditing} />
                                </div>
                            </div>

                            {/* Section 6: Ministry */}
                            <div className="p-6 border-t border-gray-100 dark:border-white/5 bg-gray-50/30 dark:bg-white/5">
                                <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4 flex items-center gap-2">
                                    <span className="material-symbols-outlined">volunteer_activism</span> Vida Ministerial
                                </h3>
                                <div className="grid grid-cols-1 gap-6">
                                    <div>
                                        <label className="block text-[10px] font-bold text-gray-500 uppercase mb-2 tracking-wider">Orden Eclesiástico</label>
                                        <div className="flex flex-wrap gap-4">
                                            {['Laico', 'Presbítero', 'Diácono', 'Ministro Laico'].map(role => (
                                                <label key={role} className="flex items-center gap-2 cursor-pointer">
                                                    <input
                                                        type="radio"
                                                        name="ministryOrder"
                                                        value={role}
                                                        checked={selectedMember.ministryOrder === role}
                                                        onChange={e => isEditing && setSelectedMember({ ...selectedMember, ministryOrder: e.target.value })}
                                                        disabled={!isEditing}
                                                        className="accent-primary"
                                                    />
                                                    <span className="text-sm text-gray-700 dark:text-gray-300">{role}</span>
                                                </label>
                                            ))}
                                        </div>
                                    </div>
                                    <Field label="Actualmente sirvo en el ministerio de" value={selectedMember.currentMinistry} onChange={v => setSelectedMember({ ...selectedMember, currentMinistry: v })} editing={isEditing} placeholder="Música, Ujieres, Escuela Dominical..." />
                                    <Field label="Dios me ha dado el don de" value={selectedMember.spiritualGifts} onChange={v => setSelectedMember({ ...selectedMember, spiritualGifts: v })} editing={isEditing} placeholder="Enseñanza, Hospitalidad, Exhortación..." />

                                    <div className="flex items-center gap-3 border bg-white dark:bg-black/20 p-3 rounded-lg border-gray-100 dark:border-white/10">
                                        <input
                                            type="checkbox"
                                            checked={selectedMember.regularAttendance || false}
                                            onChange={e => isEditing && setSelectedMember({ ...selectedMember, regularAttendance: e.target.checked })}
                                            disabled={!isEditing}
                                            className="w-5 h-5 accent-primary"
                                        />
                                        <div>
                                            <span className="block text-sm font-bold text-gray-700 dark:text-gray-300">Asistencia Regular</span>
                                            <span className="text-xs text-gray-500">Marca si asiste frecuentemente a los servicios.</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                ) : (
                    <div className="h-full flex flex-col items-center justify-center text-gray-500 opacity-60">
                        <span className="material-symbols-outlined text-6xl mb-4">badge</span>
                        <p className="text-xl font-medium">Selecciona un fiel para ver detalles</p>
                        <p className="text-sm">O crea uno nuevo con el botón +</p>
                    </div>
                )}
            </div>
        </div>
    );
}

function Field({ label, value, onChange, editing, type = "text", placeholder, options, colSpan = 1, focus }) {
    return (
        <div className={colSpan === 2 ? 'col-span-1 md:col-span-2' : colSpan === 3 ? 'col-span-1 md:col-span-3' : 'col-span-1'}>
            <label className="block text-[10px] font-bold text-gray-500 uppercase mb-1 tracking-wider">{label}</label>
            {editing ? (
                type === 'select' ? (
                    <select
                        value={value}
                        onChange={e => onChange(e.target.value)}
                        className="w-full neumorphic-inset px-3 py-2 text-sm outline-none transition-all"
                    >
                        {options.map(opt => <option key={opt} value={opt}>{opt}</option>)}
                    </select>
                ) : (
                    <input
                        type={type}
                        value={value}
                        onChange={e => onChange(e.target.value)}
                        className="w-full neumorphic-inset px-3 py-2 text-sm outline-none transition-all placeholder:text-gray-300"
                        placeholder={placeholder}
                        autoFocus={focus}
                    />
                )
            ) : (
                <div className="text-sm font-medium text-gray-800 dark:text-gray-200 min-h-[1.25rem] border-b border-transparent">
                    {value || <span className="text-gray-300 italic text-xs">Sin información</span>}
                </div>
            )}
        </div>
    );
}
